
services:

  db:
    image: postgres:17

    container_name: notevault_db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: notes

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:

    build: .

    container_name: notevault_api

    ports:
      - "8000:8000"

    depends_on:
      - db

    env_file:
      - .env.docker

volumes:
  postgres_data: